[package]
name = "tddata"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
encoding_rs = "0.8.35"
encoding_rs_io = "0.1.7"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
